version: '3'
services:

  redis_db:
    image: "redis:latest"
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - ./:/usr/src/app/  # Mount your source code as a volume to watch for changes
    environment:
      - REDIS_URL=redis://redis_db:6379